### ISSUE TITLE
Support ignoreMissingValueFiles from ArgoCD

### ISSUE THREAD

**Issue by patrickshan** [jkroepke/helm-secrets#313]
### Problem Statement

It seems that currently helm-secrets doesn't work with ignoreMissingValueFiles configuration in ArgoCD. I've already raised https://github.com/argoproj/argo-cd/issues/11853 for ArgoCD but just want to add another feature request here to see if there is anything helm-secrets could help resolve that or anyone has any idea/workaround for this issue.

### Environment

- Helm Version: 3.10.3
- Helm Secrets Version: 4.2.2

### Acceptance Criteria

- [ ] helm-secrets can works with ignoreMissingValueFiles option inside ArgoCD.

**Comment by jkroepke** [comment]
Hi, you can prepend '?' in the file path to make an values file optional

https://github.com/jkroepke/helm-secrets/wiki/Values#ignore-missing-value-files - https://github.com/jkroepke/helm-secrets/issues/276


It's technically impossible to natively support ignoreMissingValueFiles, since ArgoCD does not expose this information to helm-secrets

**Comment by patrickshan** [comment]
Thanks @jkroepke . That environment works perfectly for ArgoCD.
