### ISSUE TITLE
Using sops.yaml Azure_keyvault for China

### ISSUE THREAD

**Issue by Shaun-Harrison** [jkroepke/helm-secrets#76]
Hello

I'm trying to encrypt / decrypt a secrets.yaml file via a key in the Azure Vault, i've got a sops.yaml file as follows

`creation_rules:
    - azure_keyvault: https://[URI]/keys/[KEY]`

Which when I'm running `helm secrets enc secrets.yaml`  It errors with the following;

`[AZKV]   ERRO[0015] Failed to create Azure authorizer             error="Invoking Azure CLI failed with the following error: ERROR: CLIInternalError: The command failed with an unexpected error. Here is the traceback:\nERROR: Get Token request returned http error: 400 and server response: {\"error\":\"invalid_resource\",\"error_description\":\"AADSTS500011: The resource principal named https://vault.azure.net was not found in the tenant named [TENANT-ID]`

If you look here - https://docs.microsoft.com/en-us/azure/china/resources-developer-guide 

You'll see that `https://vault.azure.net` is the global URI, but for China it needs to be `*.vault.azure.cn`

Is there a way to be able to switch from using .net to .cn please?

**Comment by jkroepke** [comment]
Looking at https://github.com/mozilla/sops/#encrypting-using-azure-key-vault you do not have to use `https://vault.azure.net`. Use the azure CLI to generate one. I guess if you azure CLI is configured for china, the output would result a url that reference the .ch location.

In generally ask https://github.com/mozilla/sops here would be more effective since helm-secrets just using sops.
